name: CI_CD_FW

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  packages: write

jobs:
  use-reusable-workflow:
    uses: sarafogo/pipeline_templates/.github/workflows/build_nuspec.yml@main
    with:
      enableSonar: 'true'
    secrets: inherit

  deploy:
    needs: use-reusable-workflow
    uses: sarafogo/pipeline_templates/.github/workflows/deploy-lib.yml@main
    secrets: inherit
